raiJV:
	java -cp target/JuliaGenerable2-1.0-SNAPSHOT.jar prlprg.App -r=.. -t=rait.jlg -f=raif.jlg -a=raia.jlg -project=/Users/jan/Documents/raicode -discovery=true -verbose=true


std:
	java -cp target/JuliaGenerable2-1.0-SNAPSHOT.jar prlprg.App -r=.. -t=stdt.jlg -f=stdf.jlg -a=stda.jlg -discovery=false -verbose=true


